// Generated by CIRCT firtool-1.139.0
`ifndef layers_Abc_Verification_Assert	// src/main/scala/ysyx/practice.scala:6:7
  `define layers_Abc_Verification_Assert
  `include "layers-Abc-Verification.sv"	// src/main/scala/ysyx/practice.scala:6:7
`endif // not def layers_Abc_Verification_Assert
