// Generated by CIRCT firtool-1.139.0
module Abc(	// src/main/scala/ysyx/practice.scala:6:7
  input        clock,	// src/main/scala/ysyx/practice.scala:6:7
               reset,	// src/main/scala/ysyx/practice.scala:6:7
  input  [7:0] io_in,	// src/main/scala/ysyx/practice.scala:7:14
  output [7:0] io_out	// src/main/scala/ysyx/practice.scala:7:14
);

  assign io_out = io_in;	// src/main/scala/ysyx/practice.scala:6:7
endmodule

